server:
  port: 0

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092

  risk:
    weight:
      delay: 0.1
      weather: 0.2
      vendor-history: 0.3
      document-errors: 0.4

org:
  neo4j:
    migrations:
      enabled: false
